'use client';

import React, { useState, useEffect, useRef } from 'react';
import { api } from '@/lib/api';
import {
  X,
  Printer,
  Download,
  RefreshCw,
  Calendar,
  ChevronLeft,
  ChevronRight,
  FileText,
  UserCheck,
  Building,
  ArrowRightLeft,
  PackageCheck,
  ShieldCheck,
  AlertTriangle,
  Layers,
  Search,
  Clock,
  MapPin,
  FileSpreadsheet,
  CheckCircle2,
  Sparkles,
  DollarSign,
  Tag,
  Wrench,
  Truck,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { formatDate } from '@/lib/utils';

interface InventoryAuditDocumentModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function InventoryAuditDocumentModal({
  isOpen,
  onClose,
}: InventoryAuditDocumentModalProps) {
  // Period & Date State
  const [period, setPeriod] = useState<'daily' | 'weekly' | 'monthly' | 'custom'>('daily');
  const [selectedDate, setSelectedDate] = useState<string>(
    new Date().toISOString().split('T')[0]
  );
  const [customStartDate, setCustomStartDate] = useState<string>(
    new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  );
  const [customEndDate, setCustomEndDate] = useState<string>(
    new Date().toISOString().split('T')[0]
  );

  // Active view tab inside document
  const [activeSectionTab, setActiveSectionTab] = useState<'ALL' | 'ASSIGNED' | 'INSTALLED' | 'RETURNED' | 'SUMMARY'>('ALL');
  const [searchTerm, setSearchTerm] = useState('');

  // Data State
  const [reportData, setReportData] = useState<any | null>(null);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const printAreaRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      fetchAuditDocument();
    }
  }, [isOpen, period, selectedDate, customStartDate, customEndDate]);

  const fetchAuditDocument = async () => {
    try {
      setLoading(true);
      setErrorMsg(null);

      const params = new URLSearchParams();
      params.append('period', period);

      if (period === 'daily') {
        params.append('date', selectedDate);
      } else if (period === 'weekly' || period === 'monthly') {
        params.append('date', selectedDate);
      } else if (period === 'custom') {
        params.append('startDate', customStartDate);
        params.append('endDate', customEndDate);
      }

      const res = await api.get(`/api/inventory/reports/audit-document?${params.toString()}`);
      setReportData(res.data);
    } catch (err: any) {
      console.error('Failed to fetch audit document:', err);
      setErrorMsg(err.response?.data?.error || 'Failed to load inventory audit document');
    } finally {
      setLoading(false);
    }
  };

  // Date Navigator Helpers
  const handleShiftDate = (direction: 'prev' | 'next') => {
    const current = new Date(selectedDate);
    if (isNaN(current.getTime())) return;

    if (period === 'daily') {
      current.setDate(current.getDate() + (direction === 'next' ? 1 : -1));
    } else if (period === 'weekly') {
      current.setDate(current.getDate() + (direction === 'next' ? 7 : -7));
    } else if (period === 'monthly') {
      current.setMonth(current.getMonth() + (direction === 'next' ? 1 : -1));
    }

    setSelectedDate(current.toISOString().split('T')[0]);
  };

  const handleSetToday = () => {
    setSelectedDate(new Date().toISOString().split('T')[0]);
  };

  // Export to CSV
  const handleExportCSV = () => {
    if (!reportData) return;

    const docMeta = reportData.documentMeta;
    const kpi = reportData.kpiSummary;

    const lines: string[] = [];

    // Header Info
    lines.push(`"MEDIA INFOTECH - INVENTORY AUDIT & MOVEMENT REPORT"`);
    lines.push(`"Document Ref:","${docMeta.docRefId}"`);
    lines.push(`"Report Period:","${docMeta.period.toUpperCase()}"`);
    lines.push(`"Date Range:","${formatDate(docMeta.fromDate)} to ${formatDate(docMeta.toDate)}"`);
    lines.push(`"Generated At:","${new Date(docMeta.generatedAt).toLocaleString('en-IN')}"`);
    lines.push(`"Generated By:","${docMeta.generatedBy}"`);
    lines.push('');

    // Summary KPIs
    lines.push(`"=== EXECUTIVE SUMMARY ==="`);
    lines.push(`"Total Products Assigned / Dispatched:","${kpi.assignedCount} units","Valuation: ₹${kpi.assignedValuation}"`);
    lines.push(`"Total Products Used / Installed On-Site:","${kpi.installedCount} units","Valuation: ₹${kpi.installedValuation}"`);
    lines.push(`"Total Products Returned & Restocked:","${kpi.returnedCount} units","Valuation: ₹${kpi.returnedValuation}"`);
    lines.push(`"Net Warehouse Stock Movement:","${kpi.netMovement > 0 ? '+' : ''}${kpi.netMovement} units"`);
    lines.push('');

    // Section 1: Dispatched / Assigned Items
    lines.push(`"=== 1. DISPATCHED & ASSIGNED HARDWARE ==="`);
    lines.push(`"Serial / Barcode","Device Name","Model Number","Category","Dispatched To","Dispatched By","Date & Time","Condition","Unit Price (INR)","Notes"`);
    (reportData.assignedItems || []).forEach((item: any) => {
      lines.push(
        `"${item.barcode}","${item.deviceName}","${item.modelNumber || ''}","${item.category || ''}","${item.assignedTo}","${item.dispatchedBy}","${new Date(item.dispatchedAt).toLocaleString('en-IN')}","${item.condition}","${item.unitPrice || 0}","${item.logNotes || ''}"`
      );
    });
    lines.push('');

    // Section 2: Installed / Used Items
    lines.push(`"=== 2. INSTALLED & USED HARDWARE (ON-SITE) ==="`);
    lines.push(`"Serial / Barcode","Device Name","Model Number","Category","Client Site","Ticket #","Installed By","Installation Location","Installed Date","Unit Price (INR)","Notes"`);
    (reportData.installedItems || []).forEach((item: any) => {
      lines.push(
        `"${item.barcode}","${item.deviceName}","${item.modelNumber || ''}","${item.category || ''}","${item.clientName}","${item.ticketNumber}","${item.installedBy}","${item.locationDetails}","${new Date(item.installedAt).toLocaleString('en-IN')}","${item.unitPrice || 0}","${item.notes || ''}"`
      );
    });
    lines.push('');

    // Section 3: Returned Items
    lines.push(`"=== 3. RETURNED & RESTOCKED HARDWARE ==="`);
    lines.push(`"Serial / Barcode","Device Name","Model Number","Category","Return Condition","Restocked Location","Inspected By","Returned Date","Unit Price (INR)","Inspection Remarks"`);
    (reportData.returnedItems || []).forEach((item: any) => {
      lines.push(
        `"${item.barcode}","${item.deviceName}","${item.modelNumber || ''}","${item.category || ''}","${item.condition}","${item.restockedLocation}","${item.inspectedBy}","${new Date(item.returnedAt).toLocaleString('en-IN')}","${item.unitPrice || 0}","${item.notes || ''}"`
      );
    });

    const csvContent = 'data:text/csv;charset=utf-8,\uFEFF' + lines.join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `MediaInfotech_Inventory_Audit_${docMeta.docRefId.replace(/[\/\\:]/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Dedicated Print Generator for Official Document
  const handlePrint = () => {
    if (!reportData) return;

    const printWindow = window.open('', '_blank', 'width=1000,height=1100');
    if (!printWindow) {
      window.print();
      return;
    }

    const docMeta = reportData.documentMeta;
    const company = docMeta.company;
    const kpi = reportData.kpiSummary;
    const stock = reportData.currentStockSnapshot;

    const assignedRows = (reportData.assignedItems || []).map((item: any, idx: number) => `
      <tr>
        <td style="text-align: center;">${idx + 1}</td>
        <td style="font-family: monospace; font-weight: bold; color: #1e3a8a;">${item.barcode}</td>
        <td><strong>${item.deviceName}</strong> ${item.modelNumber ? `(${item.modelNumber})` : ''}</td>
        <td>${item.category || 'Hardware'}</td>
        <td style="color: #0284c7; font-weight: 600;">${item.assignedTo}</td>
        <td>${item.dispatchedBy}</td>
        <td>${new Date(item.dispatchedAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</td>
        <td style="text-align: right; font-family: monospace;">₹${(item.unitPrice || 0).toLocaleString('en-IN')}</td>
      </tr>
    `).join('');

    const installedRows = (reportData.installedItems || []).map((item: any, idx: number) => `
      <tr>
        <td style="text-align: center;">${idx + 1}</td>
        <td style="font-family: monospace; font-weight: bold; color: #065f46;">${item.barcode}</td>
        <td><strong>${item.deviceName}</strong></td>
        <td style="font-weight: 600; color: #047857;">${item.clientName}</td>
        <td style="font-family: monospace; color: #b45309; font-weight: bold;">${item.ticketNumber}</td>
        <td>${item.installedBy}</td>
        <td>${item.locationDetails}</td>
        <td>${new Date(item.installedAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</td>
        <td style="text-align: right; font-family: monospace;">₹${(item.unitPrice || 0).toLocaleString('en-IN')}</td>
      </tr>
    `).join('');

    const returnedRows = (reportData.returnedItems || []).map((item: any, idx: number) => `
      <tr>
        <td style="text-align: center;">${idx + 1}</td>
        <td style="font-family: monospace; font-weight: bold; color: #065f46;">${item.barcode}</td>
        <td><strong>${item.deviceName}</strong></td>
        <td>
          <span style="display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 10px; font-weight: bold; background: ${
            item.condition === 'EXCELLENT' || item.condition === 'GOOD' ? '#dcfce7; color: #166534;' : '#fee2e2; color: #991b1b;'
          }">
            ${item.condition}
          </span>
        </td>
        <td>${item.restockedLocation}</td>
        <td>${item.inspectedBy}</td>
        <td>${item.notes || 'Normal Check-In'}</td>
        <td>${new Date(item.returnedAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</td>
        <td style="text-align: right; font-family: monospace;">₹${(item.unitPrice || 0).toLocaleString('en-IN')}</td>
      </tr>
    `).join('');

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8" />
          <title>Inventory_Audit_Report_${docMeta.docRefId.replace(/[\/\\:]/g, '_')}</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: 'Segoe UI', Arial, Helvetica, sans-serif;
              background: #ffffff;
              color: #1e293b;
              padding: 20px;
              font-size: 11px;
              line-height: 1.4;
            }
            .document-sheet {
              max-width: 960px;
              margin: 0 auto;
              border: 1.5px solid #0f172a;
              padding: 24px 28px;
              background: #ffffff;
            }
            .header-bar {
              display: flex;
              align-items: center;
              justify-content: space-between;
              border-bottom: 2px solid #0f172a;
              padding-bottom: 12px;
              margin-bottom: 14px;
            }
            .company-title {
              font-size: 20px;
              font-weight: 800;
              color: #0f172a;
              letter-spacing: -0.5px;
            }
            .company-subtitle {
              font-size: 11px;
              color: #475569;
              margin-top: 2px;
            }
            .company-contact {
              font-size: 10px;
              color: #64748b;
              margin-top: 2px;
            }
            .doc-badge {
              text-align: right;
            }
            .doc-ref {
              font-family: monospace;
              font-weight: 800;
              font-size: 13px;
              color: #0f172a;
              background: #f1f5f9;
              padding: 4px 10px;
              border: 1px solid #cbd5e1;
              border-radius: 6px;
              display: inline-block;
            }
            .doc-type-title {
              font-size: 14px;
              font-weight: 800;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              color: #0284c7;
              margin-top: 4px;
            }
            .meta-grid {
              display: grid;
              grid-template-columns: repeat(4, 1fr);
              gap: 8px;
              background: #f8fafc;
              border: 1px solid #e2e8f0;
              border-radius: 8px;
              padding: 10px 14px;
              margin-bottom: 16px;
            }
            .meta-label {
              font-size: 9px;
              text-transform: uppercase;
              color: #64748b;
              font-weight: 700;
            }
            .meta-val {
              font-size: 11px;
              font-weight: 700;
              color: #0f172a;
              margin-top: 2px;
            }
            .kpi-row {
              display: grid;
              grid-template-columns: repeat(4, 1fr);
              gap: 10px;
              margin-bottom: 18px;
            }
            .kpi-card {
              border: 1px solid #cbd5e1;
              border-radius: 8px;
              padding: 10px 12px;
              background: #ffffff;
            }
            .kpi-card.assigned { border-left: 4px solid #0284c7; }
            .kpi-card.installed { border-left: 4px solid #10b981; }
            .kpi-card.returned { border-left: 4px solid #f59e0b; }
            .kpi-card.stock { border-left: 4px solid #6366f1; }
            .kpi-title {
              font-size: 10px;
              font-weight: 700;
              color: #475569;
              text-transform: uppercase;
            }
            .kpi-num {
              font-size: 16px;
              font-weight: 800;
              color: #0f172a;
              margin-top: 3px;
            }
            .kpi-sub {
              font-size: 10px;
              color: #64748b;
              font-family: monospace;
              margin-top: 2px;
            }
            .section-header {
              font-size: 12px;
              font-weight: 800;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              color: #0f172a;
              background: #f1f5f9;
              padding: 6px 10px;
              border-left: 4px solid #0f172a;
              margin: 16px 0 8px 0;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 12px;
              font-size: 10px;
            }
            th {
              background: #f8fafc;
              border: 1px solid #cbd5e1;
              padding: 6px 8px;
              text-align: left;
              font-weight: 700;
              color: #334155;
              text-transform: uppercase;
              font-size: 9px;
            }
            td {
              border: 1px solid #e2e8f0;
              padding: 5px 8px;
              color: #1e293b;
            }
            tr:nth-child(even) td {
              background: #fafafa;
            }
            .sign-grid {
              display: grid;
              grid-template-columns: repeat(3, 1fr);
              gap: 20px;
              margin-top: 32px;
              padding-top: 16px;
              border-top: 1.5px dashed #cbd5e1;
            }
            .sign-box {
              text-align: center;
            }
            .sign-line {
              border-top: 1px solid #0f172a;
              margin-top: 40px;
              padding-top: 6px;
              font-size: 10px;
              font-weight: 700;
              color: #0f172a;
            }
            .sign-role {
              font-size: 9px;
              color: #64748b;
            }
            @media print {
              body { padding: 0; font-size: 10px; }
              .document-sheet { border: none; padding: 0; max-width: 100%; }
              @page { size: A4 landscape; margin: 12mm 10mm 12mm 10mm; }
            }
          </style>
        </head>
        <body>
          <div class="document-sheet">
            <!-- Header Bar -->
            <div class="header-bar">
              <div>
                <h1 class="company-title">${company.name}</h1>
                <p class="company-subtitle">${company.tagline || 'Enterprise IT Solutions & Infrastructure Engineering'}</p>
                <p class="company-contact">${company.address} • GSTIN: ${company.gstin} • CIN: ${company.cin}</p>
              </div>
              <div class="doc-badge">
                <div class="doc-ref">${docMeta.docRefId}</div>
                <div class="doc-type-title">INVENTORY AUDIT MANIFEST</div>
              </div>
            </div>

            <!-- Meta Data Grid -->
            <div class="meta-grid">
              <div>
                <div class="meta-label">Audit Period</div>
                <div class="meta-val">${docMeta.period.toUpperCase()} REPORT</div>
              </div>
              <div>
                <div class="meta-label">Date Window</div>
                <div class="meta-val">${new Date(docMeta.fromDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })} - ${new Date(docMeta.toDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
              </div>
              <div>
                <div class="meta-label">Generated Timestamp</div>
                <div class="meta-val">${new Date(docMeta.generatedAt).toLocaleString('en-IN')}</div>
              </div>
              <div>
                <div class="meta-label">Authorized Issuer</div>
                <div class="meta-val">${docMeta.generatedBy}</div>
              </div>
            </div>

            <!-- Executive KPI Row -->
            <div class="kpi-row">
              <div class="kpi-card assigned">
                <div class="kpi-title">Assigned / Dispatched</div>
                <div class="kpi-num">${kpi.assignedCount} Units</div>
                <div class="kpi-sub">Value: ₹${kpi.assignedValuation.toLocaleString('en-IN')}</div>
              </div>
              <div class="kpi-card installed">
                <div class="kpi-title">Installed On-Site (Used)</div>
                <div class="kpi-num">${kpi.installedCount} Units</div>
                <div class="kpi-sub">Value: ₹${kpi.installedValuation.toLocaleString('en-IN')}</div>
              </div>
              <div class="kpi-card returned">
                <div class="kpi-title">Returned & Checked In</div>
                <div class="kpi-num">${kpi.returnedCount} Units</div>
                <div class="kpi-sub">Value: ₹${kpi.returnedValuation.toLocaleString('en-IN')}</div>
              </div>
              <div class="kpi-card stock">
                <div class="kpi-title">Net Movement & Stock</div>
                <div class="kpi-num">${kpi.netMovement > 0 ? `+${kpi.netMovement}` : kpi.netMovement} Flow</div>
                <div class="kpi-sub">In-Stock: ${stock.inStock} / Total: ${stock.totalDevices}</div>
              </div>
            </div>

            <!-- Section 1: Dispatched Hardware -->
            <div class="section-header">1. Dispatched & Assigned Hardware Manifest (${reportData.assignedItems?.length || 0} Units)</div>
            ${
              reportData.assignedItems?.length > 0
                ? `
                <table>
                  <thead>
                    <tr>
                      <th style="width: 30px;">#</th>
                      <th>Serial / Barcode</th>
                      <th>Device Name & Model</th>
                      <th>Category</th>
                      <th>Assigned Custodian</th>
                      <th>Dispatched By</th>
                      <th>Date & Time</th>
                      <th style="text-align: right;">Unit Price</th>
                    </tr>
                  </thead>
                  <tbody>${assignedRows}</tbody>
                </table>
              `
                : '<p style="font-style: italic; color: #64748b; margin-bottom: 12px;">No equipment dispatched during this audit window.</p>'
            }

            <!-- Section 2: Installed Hardware -->
            <div class="section-header">2. Installed & Consumed Hardware (Used On-Site) (${reportData.installedItems?.length || 0} Units)</div>
            ${
              reportData.installedItems?.length > 0
                ? `
                <table>
                  <thead>
                    <tr>
                      <th style="width: 30px;">#</th>
                      <th>Serial / Barcode</th>
                      <th>Device Name</th>
                      <th>Client / Site</th>
                      <th>Ticket #</th>
                      <th>Installed By</th>
                      <th>Location / GPS</th>
                      <th>Date</th>
                      <th style="text-align: right;">Value</th>
                    </tr>
                  </thead>
                  <tbody>${installedRows}</tbody>
                </table>
              `
                : '<p style="font-style: italic; color: #64748b; margin-bottom: 12px;">No hardware installed on client sites during this audit window.</p>'
            }

            <!-- Section 3: Returned Hardware -->
            <div class="section-header">3. Returned & Restocked Hardware Manifest (${reportData.returnedItems?.length || 0} Units)</div>
            ${
              reportData.returnedItems?.length > 0
                ? `
                <table>
                  <thead>
                    <tr>
                      <th style="width: 30px;">#</th>
                      <th>Serial / Barcode</th>
                      <th>Device Name</th>
                      <th>Condition</th>
                      <th>Restocked Rack</th>
                      <th>Inspected By</th>
                      <th>Inspection Remarks</th>
                      <th>Return Date</th>
                      <th style="text-align: right;">Value</th>
                    </tr>
                  </thead>
                  <tbody>${returnedRows}</tbody>
                </table>
              `
                : '<p style="font-style: italic; color: #64748b; margin-bottom: 12px;">No equipment returned during this audit window.</p>'
            }

            <!-- Sign-Off Section -->
            <div class="sign-grid">
              <div class="sign-box">
                <div class="sign-line">STORE / WAREHOUSE IN-CHARGE</div>
                <div class="sign-role">Inventory Custody & Check-In Verification</div>
              </div>
              <div class="sign-box">
                <div class="sign-line">FIELD OPERATIONS MANAGER</div>
                <div class="sign-role">Technician & Site Allocation Audit</div>
              </div>
              <div class="sign-box">
                <div class="sign-line">AUTHORIZED MANAGEMENT SIGNATORY</div>
                <div class="sign-role">Media Infotech Compliance & Accounting</div>
              </div>
            </div>
          </div>

          <script>
            window.onload = function() {
              window.print();
            };
          </script>
        </body>
      </html>
    `;

    printWindow.document.open();
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  if (!isOpen) return null;

  // Filter items in modal view based on search
  const filterList = (items: any[]) => {
    if (!items) return [];
    if (!searchTerm.trim()) return items;
    const term = searchTerm.toLowerCase();
    return items.filter(
      (i) =>
        i.barcode?.toLowerCase().includes(term) ||
        i.deviceName?.toLowerCase().includes(term) ||
        i.assignedTo?.toLowerCase().includes(term) ||
        i.clientName?.toLowerCase().includes(term) ||
        i.installedBy?.toLowerCase().includes(term) ||
        i.ticketNumber?.toLowerCase().includes(term) ||
        i.inspectedBy?.toLowerCase().includes(term)
    );
  };

  const filteredAssigned = filterList(reportData?.assignedItems || []);
  const filteredInstalled = filterList(reportData?.installedItems || []);
  const filteredReturned = filterList(reportData?.returnedItems || []);

  const meta = reportData?.documentMeta;
  const kpi = reportData?.kpiSummary;
  const stock = reportData?.currentStockSnapshot;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/85 backdrop-blur-md animate-in fade-in duration-150">
      <div className="relative w-full max-w-6xl bg-slate-900 border border-slate-800 rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[94vh]">
        {/* Top Control Bar */}
        <div className="p-4 sm:p-5 border-b border-slate-800 bg-slate-950/90 shrink-0 space-y-3">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-2xl bg-indigo-600/15 text-indigo-400 border border-indigo-500/30">
                <FileText size={22} />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h2 className="text-base font-extrabold text-white">Inventory Audit Documents & Movement Reports</h2>
                  {meta && (
                    <Badge variant="outline" className="text-[10px] bg-slate-900 border-slate-700 text-indigo-300 font-mono">
                      {meta.docRefId}
                    </Badge>
                  )}
                </div>
                <p className="text-xs text-slate-400">
                  Comprehensive audit documents for daily, weekly, and monthly tracking of Assigned, Installed, and Returned hardware.
                </p>
              </div>
            </div>

            {/* Top Action Buttons */}
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                onClick={handlePrint}
                disabled={loading || !reportData}
                className="bg-slate-900 border-slate-800 hover:bg-slate-800 text-slate-200 text-xs font-semibold gap-1.5 shadow-sm"
                title="Print Official Document / Save to PDF"
              >
                <Printer size={14} className="text-indigo-400" />
                <span>Print PDF</span>
              </Button>

              <Button
                variant="outline"
                onClick={handleExportCSV}
                disabled={loading || !reportData}
                className="bg-slate-900 border-slate-800 hover:bg-slate-800 text-slate-200 text-xs font-semibold gap-1.5 shadow-sm"
                title="Export structured audit document to Excel / CSV"
              >
                <Download size={14} className="text-emerald-400" />
                <span className="hidden sm:inline">Export CSV</span>
              </Button>

              <button
                onClick={onClose}
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition ml-1"
              >
                <X size={16} />
              </button>
            </div>
          </div>

          {/* Period Selector & Date Navigation Bar */}
          <div className="flex items-center justify-between flex-wrap gap-2 pt-1 border-t border-slate-800/80">
            {/* Period Switcher Tabs */}
            <div className="flex items-center bg-slate-900 p-1 rounded-2xl border border-slate-800">
              <button
                type="button"
                onClick={() => setPeriod('daily')}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition ${
                  period === 'daily'
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Daily
              </button>
              <button
                type="button"
                onClick={() => setPeriod('weekly')}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition ${
                  period === 'weekly'
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Weekly
              </button>
              <button
                type="button"
                onClick={() => setPeriod('monthly')}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition ${
                  period === 'monthly'
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Monthly
              </button>
              <button
                type="button"
                onClick={() => setPeriod('custom')}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition ${
                  period === 'custom'
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                Custom Range
              </button>
            </div>

            {/* Date Navigator Controls */}
            {period !== 'custom' ? (
              <div className="flex items-center gap-1.5 bg-slate-900 px-2 py-1 rounded-2xl border border-slate-800">
                <button
                  type="button"
                  onClick={() => handleShiftDate('prev')}
                  className="p-1 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition"
                  title="Previous Period"
                >
                  <ChevronLeft size={16} />
                </button>

                <input
                  type="date"
                  value={selectedDate}
                  onChange={(e) => setSelectedDate(e.target.value)}
                  className="bg-transparent text-xs font-bold text-white outline-none font-mono cursor-pointer px-1"
                />

                <button
                  type="button"
                  onClick={() => handleShiftDate('next')}
                  className="p-1 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition"
                  title="Next Period"
                >
                  <ChevronRight size={16} />
                </button>

                <button
                  type="button"
                  onClick={handleSetToday}
                  className="px-2 py-0.5 rounded-lg text-[10px] font-bold bg-slate-800 text-slate-300 hover:text-white transition ml-1"
                >
                  Today
                </button>
              </div>
            ) : (
              <div className="flex items-center gap-2 bg-slate-900 px-3 py-1.5 rounded-2xl border border-slate-800 text-xs">
                <span className="text-slate-400 font-semibold">From:</span>
                <input
                  type="date"
                  value={customStartDate}
                  onChange={(e) => setCustomStartDate(e.target.value)}
                  className="bg-slate-950 px-2 py-0.5 rounded border border-slate-800 text-xs text-white font-mono outline-none"
                />
                <span className="text-slate-400 font-semibold">To:</span>
                <input
                  type="date"
                  value={customEndDate}
                  onChange={(e) => setCustomEndDate(e.target.value)}
                  className="bg-slate-950 px-2 py-0.5 rounded border border-slate-800 text-xs text-white font-mono outline-none"
                />
              </div>
            )}
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5 custom-scrollbar">
          {errorMsg && (
            <div className="p-3.5 rounded-2xl bg-rose-950/60 border border-rose-500/50 text-rose-300 text-xs flex items-center gap-2.5">
              <AlertTriangle size={16} className="shrink-0 text-rose-400" />
              <span>{errorMsg}</span>
            </div>
          )}

          {loading ? (
            <div className="p-16 text-center text-slate-400 text-xs flex flex-col items-center justify-center gap-3">
              <RefreshCw size={24} className="animate-spin text-indigo-400" />
              <span>Compiling inventory audit reports and movement logs...</span>
            </div>
          ) : reportData ? (
            <>
              {/* EXECUTIVE KPI SUMMARY CARDS */}
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                {/* 1. Assigned / Dispatched */}
                <div
                  onClick={() => setActiveSectionTab('ASSIGNED')}
                  className={`p-4 rounded-3xl border transition cursor-pointer ${
                    activeSectionTab === 'ASSIGNED'
                      ? 'bg-blue-950/50 border-blue-500 shadow-lg shadow-blue-500/10'
                      : 'bg-slate-950/60 border-slate-800 hover:border-blue-500/40'
                  }`}
                >
                  <div className="flex items-center justify-between text-blue-400">
                    <span className="text-[11px] font-bold uppercase tracking-wider flex items-center gap-1.5">
                      <UserCheck size={14} />
                      <span>Assigned / Dispatched</span>
                    </span>
                    <Badge variant="outline" className="text-[10px] bg-blue-950 border-blue-500/30 text-blue-300">
                      Out in Field
                    </Badge>
                  </div>
                  <div className="mt-2 flex items-baseline justify-between">
                    <span className="text-2xl font-black text-white">{kpi?.assignedCount || 0}</span>
                    <span className="text-xs font-mono font-bold text-blue-300">
                      ₹{(kpi?.assignedValuation || 0).toLocaleString('en-IN')}
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-400 mt-1">Dispatched to technicians & vans</p>
                </div>

                {/* 2. Installed On-Site (Used) */}
                <div
                  onClick={() => setActiveSectionTab('INSTALLED')}
                  className={`p-4 rounded-3xl border transition cursor-pointer ${
                    activeSectionTab === 'INSTALLED'
                      ? 'bg-emerald-950/50 border-emerald-500 shadow-lg shadow-emerald-500/10'
                      : 'bg-slate-950/60 border-slate-800 hover:border-emerald-500/40'
                  }`}
                >
                  <div className="flex items-center justify-between text-emerald-400">
                    <span className="text-[11px] font-bold uppercase tracking-wider flex items-center gap-1.5">
                      <Building size={14} />
                      <span>Installed (Used)</span>
                    </span>
                    <Badge variant="outline" className="text-[10px] bg-emerald-950 border-emerald-500/30 text-emerald-300">
                      On-Site
                    </Badge>
                  </div>
                  <div className="mt-2 flex items-baseline justify-between">
                    <span className="text-2xl font-black text-white">{kpi?.installedCount || 0}</span>
                    <span className="text-xs font-mono font-bold text-emerald-300">
                      ₹{(kpi?.installedValuation || 0).toLocaleString('en-IN')}
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-400 mt-1">Consumed on client tickets</p>
                </div>

                {/* 3. Returned to Warehouse */}
                <div
                  onClick={() => setActiveSectionTab('RETURNED')}
                  className={`p-4 rounded-3xl border transition cursor-pointer ${
                    activeSectionTab === 'RETURNED'
                      ? 'bg-amber-950/50 border-amber-500 shadow-lg shadow-amber-500/10'
                      : 'bg-slate-950/60 border-slate-800 hover:border-amber-500/40'
                  }`}
                >
                  <div className="flex items-center justify-between text-amber-400">
                    <span className="text-[11px] font-bold uppercase tracking-wider flex items-center gap-1.5">
                      <ArrowRightLeft size={14} />
                      <span>Returned & Restocked</span>
                    </span>
                    <Badge variant="outline" className="text-[10px] bg-amber-950 border-amber-500/30 text-amber-300">
                      Checked In
                    </Badge>
                  </div>
                  <div className="mt-2 flex items-baseline justify-between">
                    <span className="text-2xl font-black text-white">{kpi?.returnedCount || 0}</span>
                    <span className="text-xs font-mono font-bold text-amber-300">
                      ₹{(kpi?.returnedValuation || 0).toLocaleString('en-IN')}
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-400 mt-1">Returned back to warehouse</p>
                </div>

                {/* 4. Stock Movement Balance */}
                <div
                  onClick={() => setActiveSectionTab('SUMMARY')}
                  className={`p-4 rounded-3xl border transition cursor-pointer ${
                    activeSectionTab === 'SUMMARY'
                      ? 'bg-indigo-950/50 border-indigo-500 shadow-lg shadow-indigo-500/10'
                      : 'bg-slate-950/60 border-slate-800 hover:border-indigo-500/40'
                  }`}
                >
                  <div className="flex items-center justify-between text-indigo-400">
                    <span className="text-[11px] font-bold uppercase tracking-wider flex items-center gap-1.5">
                      <ShieldCheck size={14} />
                      <span>Warehouse Stock</span>
                    </span>
                    <Badge variant="outline" className="text-[10px] bg-indigo-950 border-indigo-500/30 text-indigo-300">
                      {stock?.inStock} In Stock
                    </Badge>
                  </div>
                  <div className="mt-2 flex items-baseline justify-between">
                    <span className="text-2xl font-black text-white">
                      {kpi?.netMovement > 0 ? `+${kpi?.netMovement}` : kpi?.netMovement || 0}
                    </span>
                    <span className="text-xs font-mono font-bold text-indigo-300">
                      {stock?.totalDevices} Total Assets
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-400 mt-1">Net flow balance in period</p>
                </div>
              </div>

              {/* SEARCH & SECTION NAVIGATOR */}
              <div className="flex items-center justify-between flex-wrap gap-2 pt-2 border-t border-slate-800">
                <div className="flex items-center gap-1.5 flex-wrap">
                  <button
                    type="button"
                    onClick={() => setActiveSectionTab('ALL')}
                    className={`px-3 py-1.5 rounded-xl text-xs font-bold transition ${
                      activeSectionTab === 'ALL'
                        ? 'bg-slate-800 text-white border border-slate-700'
                        : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    All Sections
                  </button>
                  <button
                    type="button"
                    onClick={() => setActiveSectionTab('ASSIGNED')}
                    className={`px-3 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
                      activeSectionTab === 'ASSIGNED'
                        ? 'bg-blue-600/20 text-blue-300 border border-blue-500/40'
                        : 'text-slate-400 hover:text-blue-300'
                    }`}
                  >
                    <span>1. Assigned / Dispatched</span>
                    <span className="text-[10px] bg-blue-950 px-1.5 rounded-full font-mono">{kpi?.assignedCount}</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setActiveSectionTab('INSTALLED')}
                    className={`px-3 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
                      activeSectionTab === 'INSTALLED'
                        ? 'bg-emerald-600/20 text-emerald-300 border border-emerald-500/40'
                        : 'text-slate-400 hover:text-emerald-300'
                    }`}
                  >
                    <span>2. Installed (Used)</span>
                    <span className="text-[10px] bg-emerald-950 px-1.5 rounded-full font-mono">{kpi?.installedCount}</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setActiveSectionTab('RETURNED')}
                    className={`px-3 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
                      activeSectionTab === 'RETURNED'
                        ? 'bg-amber-600/20 text-amber-300 border border-amber-500/40'
                        : 'text-slate-400 hover:text-amber-300'
                    }`}
                  >
                    <span>3. Returned</span>
                    <span className="text-[10px] bg-amber-950 px-1.5 rounded-full font-mono">{kpi?.returnedCount}</span>
                  </button>
                </div>

                <div className="relative w-full sm:w-64">
                  <input
                    type="text"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    placeholder="Search by serial, device, tech..."
                    className="w-full pl-8 pr-3 py-1.5 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white placeholder-slate-500 outline-none focus:border-indigo-500"
                  />
                  <Search size={13} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-500" />
                </div>
              </div>

              {/* SECTION 1: DISPATCHED & ASSIGNED ITEMS TABLE */}
              {(activeSectionTab === 'ALL' || activeSectionTab === 'ASSIGNED') && (
                <div className="p-4 rounded-3xl bg-slate-950/60 border border-slate-800 space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wider flex items-center gap-2">
                      <UserCheck size={15} />
                      <span>1. Dispatched & Assigned Products Manifest ({filteredAssigned.length} items)</span>
                    </h3>
                    <span className="text-xs font-mono font-bold text-blue-300">
                      Total: ₹{filteredAssigned.reduce((acc, i) => acc + (i.unitPrice || 0), 0).toLocaleString('en-IN')}
                    </span>
                  </div>

                  {filteredAssigned.length === 0 ? (
                    <p className="text-xs text-slate-500 italic p-4 text-center">No assigned equipment found for this period filter.</p>
                  ) : (
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs border-collapse">
                        <thead>
                          <tr className="border-b border-slate-800 text-[10px] text-slate-400 uppercase font-semibold bg-slate-900/50">
                            <th className="py-2.5 px-3">#</th>
                            <th className="py-2.5 px-3">Serial / Barcode</th>
                            <th className="py-2.5 px-3">Device & Model</th>
                            <th className="py-2.5 px-3">Assigned To</th>
                            <th className="py-2.5 px-3">Dispatched By</th>
                            <th className="py-2.5 px-3">Date & Time</th>
                            <th className="py-2.5 px-3 text-right">Unit Price</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-800/60">
                          {filteredAssigned.map((item, idx) => (
                            <tr key={item.id || idx} className="hover:bg-slate-900/40 transition">
                              <td className="py-2.5 px-3 font-mono text-[10px] text-slate-500">{idx + 1}</td>
                              <td className="py-2.5 px-3 font-mono font-bold text-emerald-400">{item.barcode}</td>
                              <td className="py-2.5 px-3">
                                <span className="font-semibold text-white">{item.deviceName}</span>
                                {item.modelNumber && (
                                  <span className="text-[10px] text-slate-400 font-mono ml-1.5">({item.modelNumber})</span>
                                )}
                              </td>
                              <td className="py-2.5 px-3 text-blue-300 font-medium">{item.assignedTo}</td>
                              <td className="py-2.5 px-3 text-slate-300">{item.dispatchedBy}</td>
                              <td className="py-2.5 px-3 text-slate-400 font-mono text-[11px]">
                                {new Date(item.dispatchedAt).toLocaleString('en-IN', {
                                  day: '2-digit',
                                  month: 'short',
                                  hour: '2-digit',
                                  minute: '2-digit',
                                })}
                              </td>
                              <td className="py-2.5 px-3 text-right font-mono text-slate-300 font-semibold">
                                ₹{(item.unitPrice || 0).toLocaleString('en-IN')}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>
              )}

              {/* SECTION 2: INSTALLED & CONSUMED (USED) ITEMS TABLE */}
              {(activeSectionTab === 'ALL' || activeSectionTab === 'INSTALLED') && (
                <div className="p-4 rounded-3xl bg-slate-950/60 border border-slate-800 space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-2">
                      <Building size={15} />
                      <span>2. Installed & Consumed Products (Used On-Site) ({filteredInstalled.length} items)</span>
                    </h3>
                    <span className="text-xs font-mono font-bold text-emerald-300">
                      Total: ₹{filteredInstalled.reduce((acc, i) => acc + (i.unitPrice || 0), 0).toLocaleString('en-IN')}
                    </span>
                  </div>

                  {filteredInstalled.length === 0 ? (
                    <p className="text-xs text-slate-500 italic p-4 text-center">No installed/consumed equipment found for this period filter.</p>
                  ) : (
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs border-collapse">
                        <thead>
                          <tr className="border-b border-slate-800 text-[10px] text-slate-400 uppercase font-semibold bg-slate-900/50">
                            <th className="py-2.5 px-3">#</th>
                            <th className="py-2.5 px-3">Serial / Barcode</th>
                            <th className="py-2.5 px-3">Device Name</th>
                            <th className="py-2.5 px-3">Client Site</th>
                            <th className="py-2.5 px-3">Ticket #</th>
                            <th className="py-2.5 px-3">Installed By</th>
                            <th className="py-2.5 px-3">Location / GPS</th>
                            <th className="py-2.5 px-3 text-right">Value</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-800/60">
                          {filteredInstalled.map((item, idx) => (
                            <tr key={item.id || idx} className="hover:bg-slate-900/40 transition">
                              <td className="py-2.5 px-3 font-mono text-[10px] text-slate-500">{idx + 1}</td>
                              <td className="py-2.5 px-3 font-mono font-bold text-emerald-400">{item.barcode}</td>
                              <td className="py-2.5 px-3 font-semibold text-white">{item.deviceName}</td>
                              <td className="py-2.5 px-3 text-emerald-300 font-semibold">{item.clientName}</td>
                              <td className="py-2.5 px-3 font-mono text-amber-300 font-bold">{item.ticketNumber}</td>
                              <td className="py-2.5 px-3 text-slate-300">{item.installedBy}</td>
                              <td className="py-2.5 px-3 text-slate-400 truncate max-w-xs">{item.locationDetails}</td>
                              <td className="py-2.5 px-3 text-right font-mono text-slate-300 font-semibold">
                                ₹{(item.unitPrice || 0).toLocaleString('en-IN')}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>
              )}

              {/* SECTION 3: RETURNED & RESTOCKED ITEMS TABLE */}
              {(activeSectionTab === 'ALL' || activeSectionTab === 'RETURNED') && (
                <div className="p-4 rounded-3xl bg-slate-950/60 border border-slate-800 space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-2">
                      <ArrowRightLeft size={15} />
                      <span>3. Returned & Restocked Products ({filteredReturned.length} items)</span>
                    </h3>
                    <span className="text-xs font-mono font-bold text-amber-300">
                      Total: ₹{filteredReturned.reduce((acc, i) => acc + (i.unitPrice || 0), 0).toLocaleString('en-IN')}
                    </span>
                  </div>

                  {filteredReturned.length === 0 ? (
                    <p className="text-xs text-slate-500 italic p-4 text-center">No returned equipment found for this period filter.</p>
                  ) : (
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs border-collapse">
                        <thead>
                          <tr className="border-b border-slate-800 text-[10px] text-slate-400 uppercase font-semibold bg-slate-900/50">
                            <th className="py-2.5 px-3">#</th>
                            <th className="py-2.5 px-3">Serial / Barcode</th>
                            <th className="py-2.5 px-3">Device Name</th>
                            <th className="py-2.5 px-3">Condition</th>
                            <th className="py-2.5 px-3">Restocked Rack</th>
                            <th className="py-2.5 px-3">Inspected By</th>
                            <th className="py-2.5 px-3">Return Remarks</th>
                            <th className="py-2.5 px-3 text-right">Value</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-800/60">
                          {filteredReturned.map((item, idx) => (
                            <tr key={item.id || idx} className="hover:bg-slate-900/40 transition">
                              <td className="py-2.5 px-3 font-mono text-[10px] text-slate-500">{idx + 1}</td>
                              <td className="py-2.5 px-3 font-mono font-bold text-emerald-400">{item.barcode}</td>
                              <td className="py-2.5 px-3 font-semibold text-white">{item.deviceName}</td>
                              <td className="py-2.5 px-3">
                                <Badge
                                  variant={item.condition === 'EXCELLENT' || item.condition === 'GOOD' ? 'success' : 'destructive'}
                                  className="text-[10px]"
                                >
                                  {item.condition}
                                </Badge>
                              </td>
                              <td className="py-2.5 px-3 text-slate-300 font-mono text-[11px]">{item.restockedLocation}</td>
                              <td className="py-2.5 px-3 text-slate-300">{item.inspectedBy}</td>
                              <td className="py-2.5 px-3 text-slate-400 truncate max-w-xs">{item.notes}</td>
                              <td className="py-2.5 px-3 text-right font-mono text-slate-300 font-semibold">
                                ₹{(item.unitPrice || 0).toLocaleString('en-IN')}
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>
              )}
            </>
          ) : null}
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-950 flex items-center justify-between shrink-0">
          <div className="text-[11px] text-slate-400 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
            <span>Audit Document Synchronized with Master Asset Database</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 text-slate-300 hover:bg-slate-700 transition"
            >
              Close
            </button>
            <Button
              onClick={handlePrint}
              disabled={loading || !reportData}
              className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold gap-2 px-5 py-2.5 rounded-xl shadow-lg shadow-indigo-500/20"
            >
              <Printer size={15} />
              <span>Print Official Document</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
